# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'

stages:
- stage: Build
  displayName: Build image  
  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: ubuntu-latest
    steps:
    - task: Bash@3
      displayName: Build and Extract
      inputs:
        targetType: 'inline'
        script: |
          cd $(Build.SourcesDirectory)
          ls -l
          docker build \
            --build-arg ASTROLOG_VERSION=$(ASTROLOG_VERSION) \
            --build-arg LAMBDA_VERSION=$(LAMBDA_VERSION) \
            -t aws-lambda-astrolog .
          docker images
          docker save -o aws-lambda-astrolog.tar aws-lambda-astrolog
          tar xvf aws-lambda-astrolog.tar repositories
          LAYER="blobs/sha256/$(cut -d\" -f6 repositories)"
          tar xvf aws-lambda-astrolog.tar $LAYER
          tar xvf $LAYER
          rm -rf aws-lambda-astrolog.tar repositories blobs
          ls ./out
    - task: UniversalPackages@0
      inputs:
        command: 'publish'
        publishDirectory: '$(Build.SourcesDirectory)/out/'
        feedsToUsePublish: 'internal'
        vstsFeedPublish: 'e60ca8c4-457f-4edb-8eb7-8ed83edbaf79/664d455e-4358-4eb6-baa6-874a55c41ffd'
        vstsFeedPackagePublish: 'aws-lambda-$(LAMBDA_VERSION)-astrolog-$(ASTROLOG_VERSION)'
        versionOption: 'patch'
        packagePublishDescription: 'aws-lambda-$(LAMBDA_VERSION)-astrolog-$(ASTROLOG_VERSION)'
        verbosity: 'Information'
